export { builtinComponents } from './components'
export { useCatalogData } from './renderer/context'
export { ProductGridDefinition } from './components/ProductGrid/ProductGrid.definition'
export { default as PageRenderer } from './renderer/PageRenderer.vue'
import './style.css'
export * from './schema'
export * from './registry'
export * from './themes'
export { HeroDefinition } from './components/Hero/Hero.definition'
export { ProductFeatureDefinition } from './components/ProductFeature/ProductFeature.definition'
export { useCategoryFilter } from './renderer/context'